/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ConfirmacionGanador { 
    /**
     * DNI/NIF del ganador
     */
    dni: string;
    /**
     * Identificador del tipo de estado que va a cambiar
     */
    idTipoEstado: number;
}