/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Email { 
    [key: string]: any;
    /**
     * Para que correo electrónico se tiene que enviar el correo
     */
    para: string;
    /**
     * Asunto del correo electrónico
     */
    asunto: string;
    /**
     * Cuerpo del correo electrónico
     */
    cuerpo: string;
}