/**
 * Censo Hogueras
 * Censo-Hogueras
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Ganador { 
    /**
     * Email del participante
     */
    email?: string;
    /**
     * DNI/NIF del participante
     */
    dni?: string;
    /**
     * Teléfono del participante
     */
    telefono?: string;
    /**
     * Nombre de instagram
     */
    instagram?: string;
}